### ISSUE TITLE
websocket plugin configuration

### ISSUE THREAD

**Issue by osioalberto** [inmagik/react-rocketjump#58]
Consider this line: https://github.com/inmagik/react-rocketjump/blob/954bf93f8b1635ea11f204ab9a17d7c06b822704/src/plugins/ws/ws.js#L68

If the `onOpen` switch enables both the `@WS/OPEN` and `@WS/CLOSE` actions, I think it should have a better name (maybe `listenSocketStatus` or kind of that)

If instead it is intended to separate the `@WS/OPEN` and `@WS/CLOSE` actions, this is definitely a typo.

**Comment by gffuma** [comment]
Sorry is a typo :sweat_smile:

Should be:
```js
if (wsConfig.onClose) {
  ws.addEventListener('close', () => {
    // Dispatch on reducer
    subscriber.next({ type: '@WS/CLOSE' })
  })
}
```

The idea is to listen to `close` / `open` only when needed.
