### ISSUE TITLE
WIP: publish v3

### ISSUE THREAD

**Issue by bianchimro** [inmagik/react-rocketjump#78]
- [x] update docusaurus to v2 and add versioning to docs
- [ ] create docs for v3
- [x] fix changelog (typos, section "computed") and create migration guide (2 to 3), add to doc v3
- [ ] fix our dependant repos after publishing (only active developement where using @next or other tags)

**Comment by gffuma** [comment]
New home:
https://inmagik.github.io/react-rocketjump/

Docs for v2 (current stable docs):
https://inmagik.github.io/react-rocketjump/docs/

In progress docs for unreleased v3:
https://inmagik.github.io/react-rocketjump/docs/next/
